# Explicitly supplied upstream Catch2 3.8.1 amalgamation; never downloaded by CMake.
set(PULSETRACE_CATCH2_DIR "" CACHE PATH "Directory containing Catch2 3.8.1 amalgamated .hpp and .cpp")
foreach(file catch_amalgamated.hpp catch_amalgamated.cpp)
    if(NOT EXISTS "${PULSETRACE_CATCH2_DIR}/${file}")
        message(FATAL_ERROR "Supply -DPULSETRACE_CATCH2_DIR=/path/to/Catch2/extras (v3.8.1), or -DBUILD_TESTING=OFF. See README.md.")
    endif()
endforeach()
add_library(pulsetrace_catch2 STATIC "${PULSETRACE_CATCH2_DIR}/catch_amalgamated.cpp")
target_include_directories(pulsetrace_catch2 SYSTEM PUBLIC "${PULSETRACE_CATCH2_DIR}")
target_compile_features(pulsetrace_catch2 PRIVATE cxx_std_20)
find_package(Threads REQUIRED)
target_link_libraries(pulsetrace_catch2 PUBLIC Threads::Threads)
add_executable(process_discovery_tests tests/process_discovery_test.cpp)
target_include_directories(process_discovery_tests PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/src")
target_link_libraries(process_discovery_tests PRIVATE pulsetrace_core pulsetrace_catch2)
pulsetrace_target_defaults(process_discovery_tests)
add_test(NAME process_discovery COMMAND process_discovery_tests)
set_tests_properties(process_discovery PROPERTIES TIMEOUT 30)
